#Logistik Simulator Savegame
#Thu Aug 27 16:13:21 CEST 2026
aktuellerKredit=0
budget=0
calltakerStufe=0
cfgAutoTransfer=false
cfgBeschaedigung=true
cfgKrankentransport=true
cfgKrankheit=true
cfgLogistikAktiv=false
cfgSoundNotruf=true
cfgSoundStatus6=true
cfgSoundStatus7=true
hlCount=6
hl_0_anz=100
hl_0_name=Ölbindemittel
hl_1_anz=100
hl_1_name=Verbandsmaterial
hl_2_anz=100
hl_2_name=Schaummittel
hl_3_anz=100
hl_3_name=Sauerstoff O²
hl_4_anz=100
hl_4_name=PA-Gerät
hl_5_anz=100
hl_5_name=Medikamente
inGameSekunden=25200
lehrerStufe=0
level=1
matDefCount=6
matDef_0_fz=RTW,KTW,HLF,NEF
matDef_0_menge=50
matDef_0_name=Verbandsmaterial
matDef_0_preis=500
matDef_0_verb=5
matDef_0_warn=10
matDef_1_fz=RTW,NEF
matDef_1_menge=20
matDef_1_name=Medikamente
matDef_1_preis=1000
matDef_1_verb=3
matDef_1_warn=5
matDef_2_fz=RTW,KTW,NEF,HLF
matDef_2_menge=10
matDef_2_name=Sauerstoff O²
matDef_2_preis=800
matDef_2_verb=1
matDef_2_warn=5
matDef_3_fz=HLF,DLK
matDef_3_menge=10
matDef_3_name=PA-Gerät
matDef_3_preis=1500
matDef_3_verb=2
matDef_3_warn=5
matDef_4_fz=HLF
matDef_4_menge=5
matDef_4_name=Schaummittel
matDef_4_preis=2000
matDef_4_verb=5
matDef_4_warn=2
matDef_5_fz=HLF
matDef_5_menge=20
matDef_5_name=Ölbindemittel
matDef_5_preis=400
matDef_5_verb=2
matDef_5_warn=10
miss_desc=Schliesse 5 beliebige Einsaetze ab.
miss_done=false
miss_fort=0
miss_geld=2500
miss_titel=Fleissiger Disponent
miss_typ=ALLE
miss_xp=500
miss_ziel=5
speed=0
taeglicheKreditRate=0
tag=1
techGrossabnehmer=false
techKlinikCrivitz=false
techKlinikHagenow=false
techKlinikLeezen=false
vertragsCount=0
volNotruf=100
volStatus6=100
volStatus7=100
vorlage_0_art=FW
vorlage_0_desc=Tueröffnung
vorlage_0_dlk=0
vorlage_0_elw=0
vorlage_0_hatNach=false
vorlage_0_hlf=1
vorlage_0_ktw=0
vorlage_0_minLvl=1
vorlage_0_mtw=0
vorlage_0_nachProz=0
vorlage_0_nachTyp=
vorlage_0_nef=0
vorlage_0_rtw=0
vorlage_0_stichwort=H1
vorlage_0_tlf=0
vorlage_1_art=RD
vorlage_1_desc=Schnittverletzung
vorlage_1_dlk=0
vorlage_1_elw=0
vorlage_1_hatNach=false
vorlage_1_hlf=0
vorlage_1_ktw=0
vorlage_1_minLvl=1
vorlage_1_mtw=0
vorlage_1_nachProz=0
vorlage_1_nachTyp=
vorlage_1_nef=0
vorlage_1_rtw=1
vorlage_1_stichwort=R1
vorlage_1_tlf=0
vorlage_2_art=FW
vorlage_2_desc=BMA Einkaufszentrum
vorlage_2_dlk=1
vorlage_2_elw=1
vorlage_2_hatNach=true
vorlage_2_hlf=2
vorlage_2_ktw=0
vorlage_2_minLvl=3
vorlage_2_mtw=0
vorlage_2_nachProz=30
vorlage_2_nachTyp=RTW
vorlage_2_nef=0
vorlage_2_rtw=0
vorlage_2_stichwort=F3
vorlage_2_tlf=0
vorlage_3_art=FW
vorlage_3_desc=Wohnungsbrand
vorlage_3_dlk=1
vorlage_3_elw=0
vorlage_3_hatNach=true
vorlage_3_hlf=2
vorlage_3_ktw=0
vorlage_3_minLvl=2
vorlage_3_mtw=0
vorlage_3_nachProz=50
vorlage_3_nachTyp=NEF
vorlage_3_nef=0
vorlage_3_rtw=1
vorlage_3_stichwort=F2
vorlage_3_tlf=0
vorlage_4_art=RD
vorlage_4_desc=Verkehrsunfall (THL)
vorlage_4_dlk=0
vorlage_4_elw=0
vorlage_4_hatNach=true
vorlage_4_hlf=1
vorlage_4_ktw=0
vorlage_4_minLvl=4
vorlage_4_mtw=0
vorlage_4_nachProz=20
vorlage_4_nachTyp=ELW & HLF
vorlage_4_nef=1
vorlage_4_rtw=2
vorlage_4_stichwort=R2N1
vorlage_4_tlf=0
vorlage_5_art=KTP
vorlage_5_desc=Krankentransport
vorlage_5_dlk=0
vorlage_5_elw=0
vorlage_5_hatNach=false
vorlage_5_hlf=0
vorlage_5_ktw=1
vorlage_5_minLvl=1
vorlage_5_mtw=0
vorlage_5_nachProz=0
vorlage_5_nachTyp=
vorlage_5_nef=0
vorlage_5_rtw=0
vorlage_5_stichwort=KTP
vorlage_5_tlf=0
vorlage_6_art=RD
vorlage_6_desc=Atemnot
vorlage_6_dlk=0
vorlage_6_elw=0
vorlage_6_hatNach=true
vorlage_6_hlf=0
vorlage_6_ktw=0
vorlage_6_minLvl=1
vorlage_6_mtw=0
vorlage_6_nachProz=40
vorlage_6_nachTyp=NEF
vorlage_6_nef=0
vorlage_6_rtw=1
vorlage_6_stichwort=R1
vorlage_6_tlf=0
vorlagenCount=7
wache_0_fzgCount=2
wache_0_fzg_0_funk=45/46-1
wache_0_fzg_0_grund=
wache_0_fzg_0_km=0
wache_0_fzg_0_repDauer=0
wache_0_fzg_0_status=2
wache_0_fzg_0_tuev=1000
wache_0_fzg_0_typ=HLF
wache_0_fzg_1_funk=45/83-1
wache_0_fzg_1_grund=
wache_0_fzg_1_km=0
wache_0_fzg_1_repDauer=0
wache_0_fzg_1_status=2
wache_0_fzg_1_tuev=1000
wache_0_fzg_1_typ=RTW
wache_0_kennung=45
wache_0_matCount=6
wache_0_mat_0_anz=50
wache_0_mat_0_name=Ölbindemittel
wache_0_mat_1_anz=50
wache_0_mat_1_name=Verbandsmaterial
wache_0_mat_2_anz=50
wache_0_mat_2_name=Schaummittel
wache_0_mat_3_anz=50
wache_0_mat_3_name=Sauerstoff O²
wache_0_mat_4_anz=50
wache_0_mat_4_name=PA-Gerät
wache_0_mat_5_anz=50
wache_0_mat_5_name=Medikamente
wache_0_name=Wache Nord
wache_0_persCount=8
wache_0_pers_0_eigCount=0
wache_0_pers_0_fzg=45/46-1
wache_0_pers_0_gFzg=Keines
wache_0_pers_0_gStat=Bereit
wache_0_pers_0_kBis=-1
wache_0_pers_0_name=Adriano Quessel
wache_0_pers_0_planAkt=45/46-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_0_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_0_qual=MA
wache_0_pers_0_schichten=0
wache_0_pers_0_status=Bereit
wache_0_pers_0_uEnd=-1
wache_0_pers_0_uStart=-1
wache_0_pers_1_eigCount=0
wache_0_pers_1_fzg=45/46-1
wache_0_pers_1_gFzg=Keines
wache_0_pers_1_gStat=Bereit
wache_0_pers_1_kBis=-1
wache_0_pers_1_name=Fabian Stenzel
wache_0_pers_1_planAkt=45/46-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_1_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_1_qual=GF
wache_0_pers_1_schichten=0
wache_0_pers_1_status=Bereit
wache_0_pers_1_uEnd=-1
wache_0_pers_1_uStart=-1
wache_0_pers_2_eigCount=0
wache_0_pers_2_fzg=45/46-1
wache_0_pers_2_gFzg=Keines
wache_0_pers_2_gStat=Bereit
wache_0_pers_2_kBis=-1
wache_0_pers_2_name=Ian Wittka
wache_0_pers_2_planAkt=45/46-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_2_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_2_qual=TF
wache_0_pers_2_schichten=0
wache_0_pers_2_status=Bereit
wache_0_pers_2_uEnd=-1
wache_0_pers_2_uStart=-1
wache_0_pers_3_eigCount=0
wache_0_pers_3_fzg=45/46-1
wache_0_pers_3_gFzg=Keines
wache_0_pers_3_gStat=Bereit
wache_0_pers_3_kBis=-1
wache_0_pers_3_name=Lukas Muller
wache_0_pers_3_planAkt=45/46-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_3_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_3_qual=TF
wache_0_pers_3_schichten=0
wache_0_pers_3_status=Bereit
wache_0_pers_3_uEnd=-1
wache_0_pers_3_uStart=-1
wache_0_pers_4_eigCount=0
wache_0_pers_4_fzg=45/46-1
wache_0_pers_4_gFzg=Keines
wache_0_pers_4_gStat=Bereit
wache_0_pers_4_kBis=-1
wache_0_pers_4_name=Leon Schmidt
wache_0_pers_4_planAkt=45/46-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_4_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_4_qual=TM
wache_0_pers_4_schichten=0
wache_0_pers_4_status=Bereit
wache_0_pers_4_uEnd=-1
wache_0_pers_4_uStart=-1
wache_0_pers_5_eigCount=0
wache_0_pers_5_fzg=45/46-1
wache_0_pers_5_gFzg=Keines
wache_0_pers_5_gStat=Bereit
wache_0_pers_5_kBis=-1
wache_0_pers_5_name=Tyra-Jo Wittka
wache_0_pers_5_planAkt=45/46-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_5_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_5_qual=TM
wache_0_pers_5_schichten=0
wache_0_pers_5_status=Bereit
wache_0_pers_5_uEnd=-1
wache_0_pers_5_uStart=-1
wache_0_pers_6_eigCount=0
wache_0_pers_6_fzg=45/83-1
wache_0_pers_6_gFzg=Keines
wache_0_pers_6_gStat=Bereit
wache_0_pers_6_kBis=-1
wache_0_pers_6_name=Max Bauer
wache_0_pers_6_planAkt=45/83-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_6_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_6_qual=NFS
wache_0_pers_6_schichten=0
wache_0_pers_6_status=Bereit
wache_0_pers_6_uEnd=-1
wache_0_pers_6_uStart=-1
wache_0_pers_7_eigCount=0
wache_0_pers_7_fzg=45/83-1
wache_0_pers_7_gFzg=Keines
wache_0_pers_7_gStat=Bereit
wache_0_pers_7_kBis=-1
wache_0_pers_7_name=Anna Koch
wache_0_pers_7_planAkt=45/83-1,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_7_planNext=Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei,Frei
wache_0_pers_7_qual=RS
wache_0_pers_7_schichten=0
wache_0_pers_7_status=Bereit
wache_0_pers_7_uEnd=-1
wache_0_pers_7_uStart=-1
wache_0_stufe=2
wache_0_upgradeCount=0
wachenCount=1
xp=0
