#BOS Simulator Savegame
#Wed Aug 26 00:54:55 CEST 2026
abgelehnt_heute=0
budget=25000
cfg_auto=false
cfg_dmg=true
cfg_ktp=true
cfg_sick=true
lager_Binder=100
lager_Filter=100
lager_Medikamente=100
lager_Sauerstoff=100
lager_Schaum=100
lager_Verband=100
level=1
mail_count=0
mat_0_fz=RTW,KTW,HLF,NEF
mat_0_max=5
mat_0_menge=50
mat_0_name=Verband
mat_0_preis=500
mat_0_sw=
mat_0_warn=10
mat_1_fz=RTW,NEF
mat_1_max=3
mat_1_menge=20
mat_1_name=Medikamente
mat_1_preis=1000
mat_1_sw=
mat_1_warn=5
mat_2_fz=RTW,KTW,NEF,HLF
mat_2_max=1
mat_2_menge=10
mat_2_name=Sauerstoff
mat_2_preis=800
mat_2_sw=
mat_2_warn=5
mat_3_fz=HLF,DLK
mat_3_max=2
mat_3_menge=10
mat_3_name=Filter
mat_3_preis=1500
mat_3_sw=
mat_3_warn=5
mat_4_fz=HLF
mat_4_max=5
mat_4_menge=5
mat_4_name=Schaum
mat_4_preis=2000
mat_4_sw=
mat_4_warn=2
mat_5_fz=HLF
mat_5_max=2
mat_5_menge=20
mat_5_name=Binder
mat_5_preis=400
mat_5_sw=
mat_5_warn=10
mat_count=6
sekunden=26410
stat_count=0
tag=1
tech_calltaker_stufe=0
tech_ga=false
tech_klinik_crivitz=false
tech_klinik_hagenow=false
tech_klinik_leezen=false
tech_lehrer=0
tech_rh=false
tech_ws=false
vor_0_art=FW
vor_0_desc=Tuer\u00F6ffnung
vor_0_dlk=0
vor_0_elw=0
vor_0_hN=false
vor_0_hlf=1
vor_0_ktw=0
vor_0_lvl=1
vor_0_nP=0
vor_0_nT=
vor_0_nef=0
vor_0_rtw=0
vor_0_sw=H1
vor_1_art=RD
vor_1_desc=Schnittverletzung
vor_1_dlk=0
vor_1_elw=0
vor_1_hN=false
vor_1_hlf=0
vor_1_ktw=0
vor_1_lvl=1
vor_1_nP=0
vor_1_nT=
vor_1_nef=0
vor_1_rtw=1
vor_1_sw=R1
vor_2_art=FW
vor_2_desc=BMA Einkaufszentrum
vor_2_dlk=1
vor_2_elw=1
vor_2_hN=true
vor_2_hlf=2
vor_2_ktw=0
vor_2_lvl=3
vor_2_nP=30
vor_2_nT=RTW
vor_2_nef=0
vor_2_rtw=0
vor_2_sw=F3
vor_3_art=FW
vor_3_desc=Wohnungsbrand
vor_3_dlk=1
vor_3_elw=0
vor_3_hN=true
vor_3_hlf=2
vor_3_ktw=0
vor_3_lvl=2
vor_3_nP=50
vor_3_nT=NEF
vor_3_nef=0
vor_3_rtw=1
vor_3_sw=F2
vor_4_art=RD
vor_4_desc=Verkehrsunfall (THL)
vor_4_dlk=0
vor_4_elw=0
vor_4_hN=true
vor_4_hlf=1
vor_4_ktw=0
vor_4_lvl=4
vor_4_nP=20
vor_4_nT=ELW & HLF
vor_4_nef=1
vor_4_rtw=2
vor_4_sw=R2N1
vor_5_art=KTP
vor_5_desc=Krankentransport
vor_5_dlk=0
vor_5_elw=0
vor_5_hN=false
vor_5_hlf=0
vor_5_ktw=1
vor_5_lvl=1
vor_5_nP=0
vor_5_nT=
vor_5_nef=0
vor_5_rtw=0
vor_5_sw=KTP
vor_6_art=RD
vor_6_desc=Atemnot
vor_6_dlk=0
vor_6_elw=0
vor_6_hN=true
vor_6_hlf=0
vor_6_ktw=0
vor_6_lvl=1
vor_6_nP=40
vor_6_nT=NEF
vor_6_nef=0
vor_6_rtw=1
vor_6_sw=R1
vor_count=7
wache_0_c_dlk=0
wache_0_c_elw=0
wache_0_c_hlf=1
wache_0_c_ktw=0
wache_0_c_nef=0
wache_0_c_rtw=1
wache_0_fz_0_anf=0
wache_0_fz_0_ausfall=Personal fehlt
wache_0_fz_0_kennung=45-43-01
wache_0_fz_0_origAnf=0
wache_0_fz_0_rep=0
wache_0_fz_0_status=6
wache_0_fz_0_typ=HLF
wache_0_fz_1_anf=0
wache_0_fz_1_ausfall=
wache_0_fz_1_kennung=45-83-01
wache_0_fz_1_origAnf=0
wache_0_fz_1_rep=0
wache_0_fz_1_status=2
wache_0_fz_1_typ=RTW
wache_0_fz_count=2
wache_0_kennung=45
wache_0_mat_Binder=50
wache_0_mat_Filter=50
wache_0_mat_Medikamente=50
wache_0_mat_Sauerstoff=50
wache_0_mat_Schaum=50
wache_0_mat_Verband=50
wache_0_name=Wache Nord
wache_0_pers_0_fz=45-43-01
wache_0_pers_0_kBis=-1
wache_0_pers_0_lDauer=0
wache_0_pers_0_lThema=
wache_0_pers_0_name=Adriano
wache_0_pers_0_plan=45-43-01
wache_0_pers_0_planStat=Bereit
wache_0_pers_0_praef=false
wache_0_pers_0_qual=TM,TF,GF,EL,MA
wache_0_pers_0_schichten=0
wache_0_pers_0_stat=Bereit
wache_0_pers_0_uEnd=-1
wache_0_pers_0_uStart=-1
wache_0_pers_10_fz=Keines
wache_0_pers_10_kBis=-1
wache_0_pers_10_lDauer=0
wache_0_pers_10_lThema=
wache_0_pers_10_name=Tyra-Jo Wittka
wache_0_pers_10_plan=45-43-01
wache_0_pers_10_planStat=Bereit
wache_0_pers_10_praef=false
wache_0_pers_10_qual=TM
wache_0_pers_10_schichten=0
wache_0_pers_10_stat=Bereit
wache_0_pers_10_uEnd=-1
wache_0_pers_10_uStart=-1
wache_0_pers_11_fz=Keines
wache_0_pers_11_kBis=-1
wache_0_pers_11_lDauer=0
wache_0_pers_11_lThema=
wache_0_pers_11_name=Max Bauer
wache_0_pers_11_plan=45-43-01
wache_0_pers_11_planStat=Bereit
wache_0_pers_11_praef=false
wache_0_pers_11_qual=TM
wache_0_pers_11_schichten=0
wache_0_pers_11_stat=Bereit
wache_0_pers_11_uEnd=-1
wache_0_pers_11_uStart=-1
wache_0_pers_12_fz=Keines
wache_0_pers_12_kBis=-1
wache_0_pers_12_lDauer=0
wache_0_pers_12_lThema=
wache_0_pers_12_name=Anna Koch
wache_0_pers_12_plan=Keines
wache_0_pers_12_planStat=Bereit
wache_0_pers_12_praef=false
wache_0_pers_12_qual=RS
wache_0_pers_12_schichten=0
wache_0_pers_12_stat=Bereit
wache_0_pers_12_uEnd=-1
wache_0_pers_12_uStart=-1
wache_0_pers_1_fz=45-43-01
wache_0_pers_1_kBis=-1
wache_0_pers_1_lDauer=0
wache_0_pers_1_lThema=
wache_0_pers_1_name=Fabian
wache_0_pers_1_plan=45-43-01
wache_0_pers_1_planStat=Bereit
wache_0_pers_1_praef=false
wache_0_pers_1_qual=TM,TF,GF,MA
wache_0_pers_1_schichten=0
wache_0_pers_1_stat=Bereit
wache_0_pers_1_uEnd=-1
wache_0_pers_1_uStart=-1
wache_0_pers_2_fz=45-43-01
wache_0_pers_2_kBis=-1
wache_0_pers_2_lDauer=0
wache_0_pers_2_lThema=
wache_0_pers_2_name=Ian
wache_0_pers_2_plan=45-43-01
wache_0_pers_2_planStat=Bereit
wache_0_pers_2_praef=false
wache_0_pers_2_qual=TM,TF
wache_0_pers_2_schichten=0
wache_0_pers_2_stat=Bereit
wache_0_pers_2_uEnd=-1
wache_0_pers_2_uStart=-1
wache_0_pers_3_fz=Keines
wache_0_pers_3_kBis=-1
wache_0_pers_3_lDauer=0
wache_0_pers_3_lThema=
wache_0_pers_3_name=Tyra-Jo
wache_0_pers_3_plan=Keines
wache_0_pers_3_planStat=Bereit
wache_0_pers_3_praef=false
wache_0_pers_3_qual=RS,NFS,NA
wache_0_pers_3_schichten=0
wache_0_pers_3_stat=Bereit
wache_0_pers_3_uEnd=-1
wache_0_pers_3_uStart=-1
wache_0_pers_4_fz=Keines
wache_0_pers_4_kBis=-1
wache_0_pers_4_lDauer=0
wache_0_pers_4_lThema=
wache_0_pers_4_name=Stenzel
wache_0_pers_4_plan=45-83-01
wache_0_pers_4_planStat=Bereit
wache_0_pers_4_praef=false
wache_0_pers_4_qual=RS,NFS
wache_0_pers_4_schichten=0
wache_0_pers_4_stat=Bereit
wache_0_pers_4_uEnd=-1
wache_0_pers_4_uStart=-1
wache_0_pers_5_fz=45-83-01
wache_0_pers_5_kBis=-1
wache_0_pers_5_lDauer=0
wache_0_pers_5_lThema=
wache_0_pers_5_name=Adriano Quessel
wache_0_pers_5_plan=45-83-01
wache_0_pers_5_planStat=Bereit
wache_0_pers_5_praef=false
wache_0_pers_5_qual=RS,NFS
wache_0_pers_5_schichten=0
wache_0_pers_5_stat=Bereit
wache_0_pers_5_uEnd=-1
wache_0_pers_5_uStart=-1
wache_0_pers_6_fz=45-83-01
wache_0_pers_6_kBis=-1
wache_0_pers_6_lDauer=0
wache_0_pers_6_lThema=
wache_0_pers_6_name=Fabian Stenzel
wache_0_pers_6_plan=Keines
wache_0_pers_6_planStat=Bereit
wache_0_pers_6_praef=false
wache_0_pers_6_qual=RS
wache_0_pers_6_schichten=0
wache_0_pers_6_stat=Bereit
wache_0_pers_6_uEnd=-1
wache_0_pers_6_uStart=-1
wache_0_pers_7_fz=Keines
wache_0_pers_7_kBis=-1
wache_0_pers_7_lDauer=0
wache_0_pers_7_lThema=
wache_0_pers_7_name=Ian Wittka
wache_0_pers_7_plan=Keines
wache_0_pers_7_planStat=Bereit
wache_0_pers_7_praef=false
wache_0_pers_7_qual=RS
wache_0_pers_7_schichten=0
wache_0_pers_7_stat=Bereit
wache_0_pers_7_uEnd=-1
wache_0_pers_7_uStart=-1
wache_0_pers_8_fz=45-43-01
wache_0_pers_8_kBis=-1
wache_0_pers_8_lDauer=0
wache_0_pers_8_lThema=
wache_0_pers_8_name=Lukas Muller
wache_0_pers_8_plan=Keines
wache_0_pers_8_planStat=Bereit
wache_0_pers_8_praef=false
wache_0_pers_8_qual=TM
wache_0_pers_8_schichten=0
wache_0_pers_8_stat=Bereit
wache_0_pers_8_uEnd=-1
wache_0_pers_8_uStart=-1
wache_0_pers_9_fz=45-43-01
wache_0_pers_9_kBis=-1
wache_0_pers_9_lDauer=0
wache_0_pers_9_lThema=
wache_0_pers_9_name=Leon Schmidt
wache_0_pers_9_plan=Keines
wache_0_pers_9_planStat=Bereit
wache_0_pers_9_praef=false
wache_0_pers_9_qual=TM
wache_0_pers_9_schichten=0
wache_0_pers_9_stat=Bereit
wache_0_pers_9_uEnd=-1
wache_0_pers_9_uStart=-1
wache_0_pers_count=13
wachen_count=1
xp=0
