#Logistik Simulator Savegame
#Thu Aug 27 13:25:02 CEST 2026
aktuellerKredit=0
budget=25000
calltakerStufe=0
cfgAutoTransfer=false
cfgBeschaedigung=true
cfgKrankentransport=true
cfgKrankheit=true
cfgLogistikAktiv=false
cfgSoundNotruf=true
cfgSoundStatus6=true
cfgSoundStatus7=true
inGameSekunden=25250
lehrerStufe=0
level=1
speed=1
taeglicheKreditRate=0
tag=1
techGrossabnehmer=false
techKlinikCrivitz=false
techKlinikHagenow=false
techKlinikLeezen=false
vertragsCount=0
volNotruf=100
volStatus6=100
volStatus7=100
wachenCount=0
xp=0
